### ISSUE TITLE
Self-made notes in CS

### ISSUE THREAD

**Issue by mhq199657** [quarbby/links-and-resources#56]
Hi, I am currently a second-year CS student. I have made notes for most of the courses I have taken: http://www.comp.nus.edu.sg/~mahongq/revision_note.html 
Wondering whether it is suitable to put the link inside the document? Please enlighten!

**Comment by quarbby** [comment]
Hi sorry, missed this issue. Create a pull request and put it in! Do share this document with many friends, the collective wisdom makes it stronger!
